name: flutter_application_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  dev_icons: ^1.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  http: ^1.2.1
  image_picker: ^1.1.1
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  provider: ^6.1.2
  responsive_sizer: ^3.3.1
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  solar_icons: ^0.0.5
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
